---
title: "labs_6-3_exercise to R"
output: html_document
---



## R Markdown

```{r, root_1, include=FALSE}
## defines the root of the project for later use
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE,
                      results = 'hide',
                      fig.show = 'hide')
```

```{r}
library(tidyverse)
library(readr)
```

```{r}
simple_IO <- read_csv(paste0(root, "/data/simple-IO.csv"))
dim(simple_IO)
## [1] 100  11

ncol(simple_IO)

## [1] 11

nrow(simple_IO)

## [1] 100

 view(simple_IO)
```
```{r}
ncol(simple_IO)
nrow(simple_IO)
```
```{r}
summary(simple_IO)
```

##paste

```{r}
a <- c("a", "b", "c", NA)
b <- c(1:4)
c <- c(6:8, NA)
d <- c(1.3, 1.6, 6.7)
e <- as.integer(d)
f <- as.integer(a)
g <- as.numeric(a)

(z <- paste(a, b, c))
(zz <- paste0(a, b, c))
(zzz <- paste0(e, f, g))
```
```{r}
zzz

```

