---
title: "writing_function_exercize"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r}
vector1 <- as.numeric(c(1,2,3,4,5,6,7,8,9,10))
vector2 <- c("bla", "blabla", "bladiebladiabla")
a <- c(1:10)

calculate_mean <- function(x) {
  mean1 <- mean(x)
  sqrt_take <- sqrt(mean1)
  return(sqrt_take)
}

calculate_mean(x = a)
```

```{r}

  numeric_vector <- c(1:4)
  
  calculate_mean <- function(numeric_vector = NULL){
    if(is.numeric(numeric_vector)){
      message("Vector is numeric \\:-)") 
    
    } else {
      stop("Vector is not numeric \\:-(")
    }  
      sum1 <- sum(numeric_vector)
      nrow1 <- length(numeric_vector)
      mean2 <- sum1 / nrow1
      return (mean2)
  
  
  
}
calculate_mean(vector_5)

```
```{r}
##Extending a function with additional options
vector_1 <- c(1:4)
vector_2 <- c("Tiger", "Wolf", "Zebra")
vector_3 <- c(1.3, 1.6, 4.6, 7.8)
vector_4 <- as.logical(c(0,1,1,1,1,1,0,0,0,0,0,1,0))
vector_5 <- c(TRUE, FALSE, FALSE, TRUE, TRUE)

 
  calculate_mean2 <- function(numeric_vector = NULL){
    if(is.numeric(numeric_vector)){
      message("Vector is numeric \\:-)") 
    
    } else if(is.integer(numeric_vector)){
      message("Vector is integer \\:-)")      
  } else if(is.logical(numeric_vector)){
      message("Vector is logical \\:-)") 
  } else{
    
    
      stop("Vector is character \\:-(")
    }
      sum1 <- sum(numeric_vector)
      nrow1 <- length(numeric_vector)
      mean2 <- sum1 / nrow1
      return (mean2)
  
  
  
    }

  
  calculate_mean2(vector_2)
```

   

